#!/bin/sh

source "$(dirname -- "$( readlink -f -- "$0"; )";)/../android-environment/android-env.sh" @TRIPLE@

if [ -z ${CROSS_FILE} ]; then
    CROSS_FILE=./toolchain-android-@TRIPLE@.meson
fi

echo $PWD

exec meson setup \
    --prefix         ${ANDROID_PREFIX} \
    --libdir         ${ANDROID_PREFIX_LIB} \
    --libexecdir     ${ANDROID_PREFIX_LIB} \
    --bindir         ${ANDROID_PREFIX_BIN} \
    --sbindir        ${ANDROID_PREFIX_BIN} \
    --includedir     ${ANDROID_PREFIX_INCLUDE} \
    --datadir        ${ANDROID_PREFIX_SHARE} \
    --mandir         ${ANDROID_PREFIX_SHARE}/man \
    --infodir        ${ANDROID_PREFIX_SHARE}/info \
    --localedir      ${ANDROID_PREFIX_SHARE}/locale \
    --sysconfdir     ${ANDROID_PREFIX_ETC} \
    --localstatedir  /var \
    --sharedstatedir /var/lib \
    --buildtype      release \
    --wrap-mode      nofallback \
    -D               b_lto=true \
    -D               strip=true \
    --cross-file ${CROSS_FILE} \
    --default-library shared \
    "$@"
